id: ce9edeb3a2d24a0e85f8f1a131534e6b
initial_creation_type: ocr
source_metadata:
  volumes:
    9aac2e59e0bc4887847a1ab37f6b0627:
      base_file: v034.txt
      image_group_id: I1PD95879
      title: ཤེས་རབ་ཀྱི་ཕ་རོལ་ཏུ་ཕྱིན་པའི་སྙིང་པོའི་སྒྲུབ་ཐབས།
      total_pages: 1734
      volume_number: 34
